// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzegohcwawxlbjzhpwsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZWdvaGN3YXd4bGJqemhwd3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjQ4MDEsImV4cCI6MjA2MTAwMDgwMX0.Ffm7QEQsNrAHPmCtfdwNmlw5sjfQ9ctRSZbszPQ5VgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);